### ISSUE TITLE
It's Aliiiiiive! Now What?

### ISSUE THREAD

**Issue by ProtractorNinja** [clemsonacm/website#12]
[The site is up](http://www.cs.clemson.edu/acm/). Hooray! Now where do we go from here?
- **Styling Improvements**. 
  - I don't really like its current color-scheme, personally; I think the colors need some more fine-tuning.
  - How do we, or do we even want to, add margins and padding? They'd take away from that emacs feeling, but is that more important than readability? For example, I think the descriptions on the officer page should be indented.
- **Content Revisions**. 
  - I like this initial round of pages, but I think the copy (er, text) is written kind of oddly right now. I'll probably work on that this weekend.
- **Ease-of-development**. 
  - Should we start using something like Sass to make style work easier on developers?
  - How does this site get deployed? 
    - Is it easy to update?

These are questions for all of us to ponder, moving forward. Good job on the site so far!

**Comment by robertu94** [comment]
For the margins and padding, I think that we could add some small padding (1-2cm) without sacrificing too much theme.

**Comment by ProtractorNinja** [comment]
What's a centimeter?

**Comment by robertu94** [comment]
Closing this in favor of a dedicated issue.
